name: "creation of CI test workflow"
on:
  push: 
    branch: "master"
jobs: 
  test:
    runs-on: ubuntu-latest

    steps:

    - name: "checking out repository"
      uses: actions/checkout@v3

    - name: "setting java development environment"
      uses: actions/setup-java@v4

      with: 
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: "watching pwd"
      run: pwd

    - name: "running build test"
      run: mvn clean test